// data.jsx — content + design tokens for the Education / Journey section.
// Exposed as window.EduData and window.EduTokens.

const TOKENS = {
  bg:         "#0b1120",
  bgDeep:     "#070b16",
  panel:      "rgba(15, 23, 42, 0.72)",
  panelSolid: "#0f172a",
  border:     "rgba(148, 163, 184, 0.12)",
  borderHot:  "rgba(96, 165, 250, 0.55)",
  text:       "#e2e8f0",
  textDim:    "#94a3b8",
  textMuted:  "#64748b",
  accent:     "#60a5fa",
  accentSoft: "#93c5fd",
  accentGlow: "rgba(96, 165, 250, 0.18)",
  accentTint: "rgba(96, 165, 250, 0.07)",
  serif:      `"Fraunces", Georgia, serif`,
  sans:       `"Inter", "Helvetica Neue", system-ui, sans-serif`,
  mono:       `"JetBrains Mono", "SF Mono", Menlo, monospace`,
  radius:     "16px",
  radiusSm:   "10px",
};

const ENTRIES = [
  {
    id: "ottawa",
    index: 1,
    flag: "🇨🇦",
    code: "CA",
    country: "Canada",
    city: "Ottawa",
    lat: 45.4215,
    lng: -75.6972,
    dateRange: "Jan 2022 — Jun 2023",
    program: "M.Eng",
    degree: "M.Eng Data Science & AI",
    institution: "University of Ottawa",
    standing: "A+ · GPA 4.0 / 4.0",
    advisors: "Dr. Murat Simsek",
    thesis: {
      title: "Production Spoken Language Identification at Scale",
      abstract:
        "A streaming LID system that classifies 7 languages from short audio chunks (3–8 seconds) with strong accuracy. Deployed as an API to a downstream ASR-style processing layer for multilingual voice applications. Contributions: comparative evaluation of ML, CNN, and raw-signal deep learning approaches, and development of a Conv1D-based model that generalizes well under real-world conditions (e.g., noisy and out-of-distribution audio).",
    },
    honors: [
      "Full DEBI Scholarship — Ministry of ICT + Univ. of Ottawa",
      "Top 5% cohort",
    ],
    coursebook: [
      "Data Science Applications (DTI 5125)",
      "Fundamentals for Applied Data Science (DTI 5126)",
      "Applied Machine Learning (ELG 5255)",
      "Ubiquitous Sensing for Smart Cities (ELG 5142)",
      "Cloud Analytics (ELG 5166)",
      "AI for Cyber Security (ELG 7186)",
      "Learning-Based Computer Vision (ELG 7186)",
      "Topics in Industry Practice (GNG 5310)",
      "Electrical Engineering Project (ELG 5901)",
    ],
    skills: [
      { name: "PyTorch",                       level: 95 },
      { name: "TensorFlow",                    level: 88 },
      { name: "Speech / Audio ML",             level: 92 },
      { name: "Time-series modeling",          level: 85 },
      { name: "MLOps (Docker, K8s, Triton)",   level: 85 },
      { name: "Model serving & evals",         level: 80 },
    ],
    takeaway:
      "Built my strongest foundation in ML, deployment, and real-world language systems.",
  },
  {
    id: "cairo",
    index: 2,
    flag: "🇪🇬",
    code: "EG",
    country: "Egypt",
    city: "Cairo",
    lat: 30.0444,
    lng: 31.2357,
    dateRange: "Sep 2016 — Jul 2020",
    program: "B.Sc.",
    degree: "B.Sc. Computer Science & Mathematics",
    institution: "Helwan University",
    standing: "2nd in Class · GPA 3.85 / 4.0",
    advisors: "Dr. Ahmed Azzat",
    thesis: {
      title: "Movie Recommendation System (\"Break\")",
      abstract:
        "Designed and implemented \"Break\", a multi-usage mobile recommender system for Android that suggests movies and media content using a combination of demographic and content-based filtering (genres, keywords, and credits). The system integrates TMDB APIs to fetch up-to-date data and leverages user preferences and interaction history (e.g., favorites and browsing behavior) to generate personalized recommendations. Built as a proof-of-concept prototype, the application includes features such as movie exploration, trailers, and similar-item recommendations, and was evaluated through a small user group to assess usability, relevance of recommendations, and overall user experience.",
    },
    honors: [
      "Graduated second in class",
    ],
    coursebook: [
      "Linear Algebra & Optimization",
      "Discrete Mathematics",
      "Probability & Statistics",
      "Algorithms & Complexity",
      "Operating Systems",
      "Database Systems",
      "Numerical Methods",
      "Machine Learning Foundations",
      "Compilers",
    ],
    skills: [
      { name: "Mathematical foundations", level: 95 },
      { name: "Algorithm design",         level: 90 },
      { name: "C++ / Systems",            level: 82 },
      { name: "SQL & data modeling",      level: 80 },
      { name: "Java",                     level: 85 },
      { name: "Python",                   level: 88 },
      { name: "System design",            level: 78 },
      { name: "GUI development",          level: 75 },
      { name: "Image processing",         level: 78 },
    ],
    takeaway:
      "Built the mathematical and computational foundation behind every model I've shipped since.",
  },
  {
    id: "zurich",
    index: 3,
    flag: "🇨🇭",
    code: "CH",
    country: "Switzerland",
    city: "Zurich",
    lat: 47.3769,
    lng: 8.5417,
    dateRange: "Jul — Aug 2023",
    program: "Summer School",
    degree: "Summer School Deep Dive into Blockchain",
    institution: "University of Zurich",
    standing: "Completed program requirements · 6 ECTS",
    advisors: "Claudio J. Tessone",
    thesis: {
      title: "Transparent Supply Chain Tracking on the BNB Chain Platform (ChainTrack)",
      abstract:
        "A blockchain-based supply chain tracking prototype built on the BNB Chain platform to improve transparency, traceability, and trust across supply chain operations. Smart contracts were used to securely record and verify transactions, enabling stakeholders to track products from origin to delivery with immutable data. Implemented core features including transaction recording, role-based system interactions (admin, manufacturer, distributor, customer), and a user interface for managing and viewing supply chain data. The system supports real-time updates and helps address common challenges such as data manipulation, lack of visibility, and inefficient manual processes. Developed as a team-based prototype and evaluated based on functionality, usability, and its effectiveness in demonstrating secure and transparent tracking.",
    },
    honors: [
      "Completed program requirements",
    ],
    coursebook: [
      "Distributed Consensus & Blockchain Fundamentals",
      "Cryptographic Primitives",
      "Smart Contract Engineering",
      "Blockchain Ecosystems & Platforms",
      "Tokenization & Cryptoeconomics",
      "DeFi & Web3 Applications",
      "Blockchain Governance & Regulation",
    ],
    skills: [
      { name: "Blockchain fundamentals",     level: 80 },
      { name: "Decentralized systems",       level: 75 },
      { name: "Cryptography fundamentals",   level: 70 },
      { name: "Solidity & EVM",              level: 65 },
    ],
    takeaway:
      "Expanded my perspective on applying blockchain technology to real-world systems such as supply chains and decentralized applications.",
  },
];

Object.assign(window, { EduTokens: TOKENS, EduEntries: ENTRIES });
